# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fileuser:
            id: app.file_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        password:
            pattern: ^/login/password
            anonymous: ~

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER_IP, ips: [89.197.61.218, 79.173.165.58, 92.207.141.247] }
        - { path: ^/, roles: ROLE_LOGVIEWER }

    encoders:
        AppBundle\Security\User\User:
            algorithm: bcrypt
            cost: 12