# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    # These are the names of the services as we can't inject the services 
    # themselves using a parameter. The finder service derefences them.
    app.params.logFinders:
        - app.logFinder.apacheAccess
        - app.logFinder.apacheError
        - app.logFinder.php
        - app.logFinder.magento
        - app.logFinder.magentoReport
  
    app.params.apacheAccessFinder: AppBundle\Finder\ApacheAccessFinder
    app.params.apacheAccessLog: AppBundle\Model\ApacheAccessLog

    app.params.apacheErrorFinder: AppBundle\Finder\ApacheErrorFinder
    app.params.apacheErrorLog: AppBundle\Model\ApacheErrorLog

    app.params.phpFinder: AppBundle\Finder\PhpFinder
    app.params.phpLog: AppBundle\Model\PhpLog

    app.params.magentoFinder: AppBundle\Finder\MagentoFinder
    app.params.magentoLog: AppBundle\Model\MagentoLog

    app.params.magentoReportFinder: AppBundle\Finder\MagentoReportFinder
    app.params.magentoReport: AppBundle\Model\MagentoReport


services:
    app.project:
        class: AppBundle\Model\Project

    app.logFinder:
        class: AppBundle\Finder\LogfileFinderService
        arguments: [ %app.params.logFinders%, '@service_container' ]

    app.logFinder.apacheAccess:
        class: '%app.params.apacheAccessFinder%'
        arguments: [ null, '%app.params.apacheAccessLog%', null, '@app.project' ]

    app.logFinder.apacheError:
        class: '%app.params.apacheErrorFinder%'
        arguments: [ null, '%app.params.apacheErrorLog%', null, '@app.project' ]

    app.logFinder.php:
        class: '%app.params.phpFinder%'
        arguments: [ '*', '%app.params.phpLog%', null, '@app.project' ]

    app.logFinder.magento:
        class: '%app.params.magentoFinder%'
        arguments: [ '*', '%app.params.magentoLog%', null, '@app.project' ]

    app.logFinder.magentoReport:
        class: '%app.params.magentoReportFinder%'
        arguments: [ '*', '%app.params.magentoReport%', null, '@app.project' ]

    app.file_user_provider:
        class: AppBundle\Security\User\FileUserProvider
        arguments: [ '%kernel.root_dir%/config/passwd', '@logger' ]